### PR TITLE
Misc Fixes

### PR DESCRIPTION
**Pull request by JakeDaBoss**
On-going efforts as we find things in the rounds.

### CODE REVIEW

**Review by NanakoAC — APPROVED** [review]
Approved by me, but get snype to approve mapping changes too

**Comment by JakeDaBoss** [comment]
Reverted back to draft as I'm working on some things.

**Comment by JakeDaBoss** [comment]
Ready for re-review, @NanakoAC

**Comment by JakeDaBoss** [comment]
@WestHybrid your approval is needed on: https://github.com/DS-13-Dev-Team/DS13/pull/599/commits/e45adc15ee59e7bd848aa1013d6dfe94e472fd0f

**Pull request merged**
