### PR TITLE
Janitor

### LINKED ISSUE #355: [Suggestion] Add Janitor Role
#### Description of issue
There is currently no Janitor/Custodian role! Also, there are missing items in the janitorial closet I will list below!

#### Difference between expected and actual behavior
The expected behavior is there is a janitorial role with more janitor stuff in the closet, the actual behavior is there is not that.

#### Steps to reproduce 
Please consider adding these items to the Janitorial closet:
A mop (or two) , a bar of soap, three more wet signs (if we are going to have two janitorial carts), mouse traps, a trash bag, a light replacer and replacement lights. 

Additionally, an occupation for sanitation technician/custodian/janitor needs to be added, but if all the items spawn in the closet maybe we have them go to their closet to get geared up. That would mean 2 of each item if there are only 2 slots for this occupation.

#### Specific information for locating
Sorry I do not have the typepaths :-(

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 43f9e96a434aebc7c1ea774215205932d2a5a66c - dev - 2020-05-14
Game ID: b60-cOv2
Current map: USG Ishimura

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

### PR DESCRIPTION
**Pull request by Afya212**
Adds the Janitor role, exactly what you would expect. Has one job slot but could easily be made two with the current Janitor closet.
close #355

Adds Janitor Role
Minor edits to janitor closet

### CODE REVIEW

**Comment by NanakoAC** [comment]
some sort of cleaning role will prove quite important in future, we'll see what snype says

**Comment by Ketrai** [comment]
I feel like a janitor role is fair. Besides, it can help against pukers.

**Comment by Snypehunter007** [comment]
I'm sort of conflicted. I don't think Janitor role is the best thing at the moment. Currently, the roles are already split quite a bit by our low population. Spitting it further is sort of pointless.

Granted, the janitor role, as proposed, is one one person but that also works against it. For a ship so large, having only one janitor not only puts a little bit of pressure on the suspension of disbelief, but from a gameplay perspective, engineers already do everything a janitor could do, even if they don't probably clean as much as they should have. Eliminating the possibility for maintenance and janitorial possibilities from the engineering role however leaves engineers with literally nothing to do until the Necromorphs spawn. They cannot tinker with atmospherics and the opportunities for retrofitting a room and changing it are very limited. 

Not only that but there are more engineers slots currently in comparison to the proposed Janitor slots, allowing for there to be a higher number of engineer-janitors if they are pressed into it.

**Review by Snypehunter007 — COMMENTED** [review]
I'm sort of conflicted. I don't think Janitor role is the best thing at the moment. Currently, the roles are already split quite a bit by our low population. Spitting it further is sort of pointless.

Granted, the janitor role, as proposed, is one one person but that also works against it. For a ship so large, having only one janitor not only puts a little bit of pressure on the suspension of disbelief, but from a gameplay perspective, engineers already do everything a janitor could do, even if they don't probably clean as much as they should have. Eliminating the possibility for maintenance and janitorial possibilities from the engineering role however leaves engineers with literally nothing to do until the Necromorphs spawn. They cannot tinker with atmospherics and the opportunities for retrofitting a room and changing it are very limited.

Not only that but there are more engineers slots currently in comparison to the proposed Janitor slots, allowing for there to be a higher number of engineer-janitors if they are pressed into it.

**Comment by NanakoAC** [comment]
allow anyone to access custodial gear, but having a specialised role will be good for it. Right now runes, bloodstains etc are everywhere, theres a lot of work to do, and these things will become important later with sanity effects

Engineers will have plenty to do in future. I've already recently added a lot of fortification crafting options, they'll be doing weapon crafting too, and repairing crew objectives to keep the ship running

**Comment by Afya212** [comment]
Anyone with Maint access can get into the Custodian stuff, as it is now as well which I think is fair.

**Comment by JakeDaBoss** [comment]
@Snypehunter007 I think it might be time to revisit this.

**Comment by NanakoAC** [comment]
too outdated to merge, we'll remake this when it's time. Janitors will be added in future when the time is right

**Pull request closed without merging**
