### PR TITLE
colony mapping + one ishimura room

### PR DESCRIPTION
**Pull request by karlodayo**
- shrunk colony and balanced it in terms of human hiding
- added some new features and renovations to colony
- updated ishi clothing room.

### CODE REVIEW

**Review by DTraitor — APPROVED** [review]

**Comment by nianoru** [comment]
Going to retest colony map to see if everything seems to work properly.

**Comment by nianoru** [comment]
testing map to see if everythin work good

**Comment by karlodayo** [comment]
might have to tweak it later, just add it temporarily to the next weekend session till i confirm its good to go.

**Review by DTraitor — APPROVED** [review]
Looks nice

**Pull request merged**
