### PR TITLE
TGS Server support.

### PR DESCRIPTION
**Pull request by DeadLineSS13**
Adds DMAPI for TGS Servers.
P.S. You can start server without TGS.

### CODE REVIEW

**Comment by DeadLineSS13** [comment]
Don't forget add labels.

**Comment by NanakoAC** [comment]
This contains no introduction, i'm not sure what the purpose of all this is. Its going to need some elaboration.

What does this do? What is TGS ?

**Comment by DeadLineSS13** [comment]
> This contains no introduction, i'm not sure what the purpose of all this is. Its going to need some elaboration.
> 
> 
> 
> What does this do? What is TGS ?

https://tgstation.github.io/tgstation-server/features.html

**Comment by Ketrai** [comment]
/TG/ has exquisite server hosting and ddos protection. So this could be useful if looked into proper

**Review by JakeDaBoss — APPROVED** [review]
I've used this program before, and it's a major feature to have and a massive coup for our hosting efforts. If needed, I'll make myself available to provide assistance.

**Comment by DeadLineSS13** [comment]
Don't merge this. TGS json need.

**Comment by JakeDaBoss** [comment]
> Don't merge this. TGS json need.

Let me know when it's all good.

**Review by JakeDaBoss — APPROVED** [review]

**Comment by JakeDaBoss** [comment]
Awaiting practical test from RU-DS13 come Friday.

**Comment by DeadLineSS13** [comment]
image
Check TGS Bot. TGS work good. Tomorrow final tests.

**Comment by DeadLineSS13** [comment]
image
This work good and ready for merge.

**Comment by DeadLineSS13** [comment]
image

**Comment by JakeDaBoss** [comment]
@WestHybrid Only merge this if you're able to work on it with me. No sooner.

**Comment by DeadLineSS13** [comment]
1E6DD240-4F89-4705-A8D7-3245689E7801 Now bot can this.

**Comment by DeadLineSS13** [comment]
PR Broken. DON'T MERGE THIS

**Comment by JakeDaBoss** [comment]
I will perform a test on this during the next Honored Guest test for the Tram Deck. Two birds, one stone.

**Comment by JakeDaBoss** [comment]
Due to my leave of absence, I will not be able to test this out at all. Much like the tram deck, and the earthgov agent, I have to put this task down and instead revise how we'd be implementing this.

You should reach out to West, and see if you can't coach him through it yourself, as I won't do so at this time. Thank you for your work however, and I maintain this would make an excellent and streamlined addition.

**Pull request merged**
