### PR TITLE
Delete var/ in proc

### PR DESCRIPTION
**Pull request by DeadLineSS13**
First step fixes run_linters.

### CODE REVIEW

**Comment by Terror4000rus** [comment]
I see hours of pain

**Comment by Terror4000rus** [comment]
DeadLineSS13 after cleaning up code
<details>

image

</details>

**Comment by RuneQuester** [comment]
what is this

**Comment by DeadLineSS13** [comment]
> what is this

PR with deleting var/ in contains proc.

**Comment by NanakoAC** [comment]
why?

**Comment by DeadLineSS13** [comment]
> why?
Clean code. And also to lighten the weight of the project, at least by 12k var/

**Comment by DeadLineSS13** [comment]
Closed, because we don’t need this.

**Pull request closed without merging**
