### PR TITLE
Adds a little evil to the chef's microwave prowess.

### PR DESCRIPTION
**Pull request by Ketrai**
Necro.

JELLO.

### CODE REVIEW

**Review by JakeDaBoss — CHANGES_REQUESTED** [review]
GOD PLEASE NO.

**Review by NanakoAC — APPROVED** [review]
seems a fun little thing

**Comment by Ketrai** [comment]
actually dun merge yet, gonna work on this a lill more

**Comment by Snypehunter007** [comment]
I'm confused, what is this, @Ketrai ?

**Comment by Ketrai** [comment]
Just FYI, it's only a 7,61% chance to spawn anything other than default jello. And it's extremely, extremely rare to get something as big as a tormentor or a tripod.

**Review by JakeDaBoss — APPROVED** [review]
Balance-wise okay. Gonna have to see what happens here and adjust accordingly.

**Pull request merged**
