### PR TITLE
fix suspension field generator ui

### LINKED ISSUE #1176: Suspension Field Generator non-functional.
#### Description of issue:
none of the buttons work on the suspension field generator in xenoarch. it doesn't turn on, lock, refresh, or close

#### Difference between expected and actual behavior:
Should work.

### PR DESCRIPTION
**Pull request by Evankhell561**
This machine uses an internal battery however it will not work in an area without power, this fixes it.
fix: #1176 
:cl:
fix: suspension field generator ui
/:cl:

### CODE REVIEW

**Comment by Evankhell561** [comment]
image

**Review by JakeDaBoss — APPROVED** [review]
Looks good.

**Review by JakeDaBoss — CHANGES_REQUESTED** [review]
On second glance. Please include a changelog .yml.

**Comment by Evankhell561** [comment]
> On second glance. Please include a changelog .yml.

What do you mean?

**Comment by JakeDaBoss** [comment]
> > On second glance. Please include a changelog .yml.
> 
> What do you mean?

Go to HTML -> Changelogs, and copy the example.yml. Fill out your ckey, and add - in detail but not too much detail obviously - what you've fixed.

UI changes mean nothing to the average player. So i.e.

  - fix: "Fixed a common issue with the Suspension Field Generator that caused it to go non-functional."

**Comment by JakeDaBoss** [comment]
Sorry for the confusion.

Git automated runjobs don't really... Run, half the time.

**Pull request merged**
