### PR TITLE
Fixes necros spawning outside in a tram spawn.

### PR DESCRIPTION
**Pull request by Ketrai**
Necros were spawning in space here and often breached the ship because of it.

### CODE REVIEW

**Comment by NanakoAC** [comment]
This seems like a code problem rather than mapping

can you show what exactly the issue is, and what you've done to fix it?

**Comment by Ketrai** [comment]
> This seems like a code problem rather than mapping
> 
> can you show what exactly the issue is, and what you've done to fix it?

It looks like a mapping error coz there's some non-space area outside the ship. Where they were spawning. Otherwise necros don't spawn outside.

**Comment by Snypehunter007** [comment]
I can fix this on my current tram deck branch and merge it when I finish that if you can give me a picture of the problem, but I'm waiting for someone to fix double doors before I can proceed.

**Comment by NanakoAC** [comment]
closing since snype says he'll fix it

**Pull request closed without merging**
