### PR TITLE
CBT update

### PR DESCRIPTION
**Pull request by DeadLineSS13**
## About this PR
This PR port CBT system from tgstation/tgstation#55373 and tgstation/TerraGov-Marine-Corps#7130

### CODE REVIEW

**Comment by DTraitor** [comment]
If you don't use VS Code then you run `tools/build/build.bat`

**Comment by DeadLineSS13** [comment]
> If you don't use VS Code then you run `tools/build/build.bat`

After merge TGUI v4 this will be required, but not required at this time.

**Comment by stylemistake** [comment]
Outdated

https://github.com/tgstation/tgstation/commits/master/tools/build

**Comment by DeadLineSS13** [comment]
> Outdated

Thx.

**Comment by DeadLineSS13** [comment]
Common Build Tool is thing needed for fast compiles project where need compile not just the DM. Example TGUI need also a separate compilation so that it updates the resources. And in CBT added TGS scripts

**Review by NanakoAC — APPROVED** [review]

**Pull request merged**
