### PR TITLE
Ladders Stronk

### LINKED ISSUE #319: [Bug] Puker Acid Melts Ladders
This is bad because ladders are very important. Title.

### PR DESCRIPTION
**Pull request by Afya212**
Makes ladders indestructible.
Fixes #319

### CODE REVIEW

**Review by NanakoAC — COMMENTED** [review]
Have you tested this? I significantly overhauled structure damage

**Comment by NanakoAC** [comment]
there are also broken ladder sprites in the same file as the existing ones.  a bit incomplete though (missing floor/ceiling hatch versions). with a little work on photoshop that could be done, and we could have ladders enter a broken state without deleting themselves, from which they could be repaired

Feel up to doing that? or too far beyond scope

**Comment by Afya212** [comment]
Forgot to test puker, seems that it was an old issue, ree. I always test my code before making a PR of course. I'd still argue it's useful in same way it is with stairs, having them blow up can just ruin flow and make it far more inconvenient. 

Spriting is one thing I don't touch at all though, beyond scope.

**Review by NanakoAC — APPROVED** [review]
seems fine to implement as-is

**Pull request merged**
