### PR TITLE
Workflows and update Readme.

### PR DESCRIPTION
**Pull request by DeadLineSS13**
Standards workflows.

### CODE REVIEW

**Comment by DeadLineSS13** [comment]
Don't forget add labels for these workflows.

**Comment by DeadLineSS13** [comment]
And change this «https://img.shields.io/discord/*channel id*»

**Comment by DeadLineSS13** [comment]
And add bots map diff and icon diff.

**Comment by NanakoAC** [comment]
are these run on github itself? I've not used workflows like these before.

What's your comment about regarding a change?

**Comment by DeadLineSS13** [comment]
> are these run on github itself? I've not used workflows like these before.
> 
> 
> 
> What's your comment about regarding a change?

￼Yep.

About changes? What do you want to hear about them?

**Comment by DeadLineSS13** [comment]
Example: https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/463426738

**Review by NanakoAC — APPROVED** [review]

**Review by NanakoAC — APPROVED** [review]

**Pull request merged**
