### PR TITLE
Another round of fixing debug...

### PR DESCRIPTION
**Pull request by JakeDaBoss**

### CODE REVIEW

**Review by NanakoAC — DISMISSED** [review]
approved, rapid merge recommended

**Comment by NanakoAC** [comment]
Please don't make unrelated changes to an already approved PR, i'll have a look over this agaom

**Comment by JakeDaBoss** [comment]
Whether you re-review something or review a new PR makes no difference. Be happy I'm still providing fixes as it stands.

**Comment by ghost** [comment]
We appreciate the fixes but Nanako is correct, adding unrelated fixes to hotfixes makes it harder to merge the necessary material right away if something else is contested. Nevertheless, merging.

**Pull request merged**
