### PR TITLE
Minor loadout clothing addition

### PR DESCRIPTION
**Pull request by Pebblesthe2nd**
Four pieces of clothing for loadouts for a little added customisation.

For MD:s : EMS jacket
Engineer: Hazard overall
Cargo people: Bomber jacket
Civilians: Leather jacket

Just a bit of optional color for characters that doesn't go to the bar with their full RIG deployed. Adjusted their descriptions a little.

### CODE REVIEW

**Comment by Ketrai** [comment]
Again, would really like proper screenshots in these.

**Comment by Snypehunter007** [comment]
> 
> 
> Again, would really like proper screenshots in these.

He added them to the loadout, he didn't replace the icons this time.

That said, personally, going to go with a negative for the proposed changes.

**Comment by Pebblesthe2nd** [comment]
Sprite-0001
Looks like this.
It makes no sense to me that the hazard jumpsuit is almost civilian only rather than engineers since it only spawn in maints for some strange reason. As for the others, just minor flavour items, having the chef have a optional jacket to cover his Mario getup when on break doesn't seem particularly offensive to me.
Also trivial to edit should something become overused or problematic.

**Comment by Ketrai** [comment]
As much as I like these we're aiming to reduce the amount of non dead space clothing in the loadout down the line. Not increase it.

**Pull request closed without merging**
