### PR TITLE
Misc fixes

### LINKED ISSUE #125: BUG: Multiple spelling errors with Necromorph structure tiles
#### Description of issue
- Corruption tiles are currently capitalized. So when you examine them it displays, **"That's Corruption"**.
- The rest of the structures have the same problem:
   - Propagators, **"That's Propagator"**
   - Eyes, **"That's Eye"**
   - Nests, **"That's Nest"**

#### Steps to reproduce 
- Examine Necromorph structures.

### LINKED ISSUE #307: [Suggestion] Security QoL improvements
1. Give security bowman headsets. The HUDs give flash protection but there is no bang protection, even inside a rig. 

2. Have gas masks/equivalent added to brig so officers can protect themselves from tear gas. Currently you have to scavenge them from maint or lockers.

3. Make gas mask/equivalent a small item so that it is able to fit in your holster belt, pocket or webbing vest.

4. Add the ability to put weapons on the suit slot such as pulse rifles and riot shields.

5. Add basic armor vests in lockers to use when there is not a RIG available.

6. Allow lockers to be locked and windoors to be closed without automatically opening themselves.

7. Clicking in general with an active gun in your hand, will cause it to fire. This includes but is not limited to examining an object, attempting to use aim mode, and whatever else. Change it so it doesn't do this.

### LINKED ISSUE #418: [BUG] Can't attach accessories to plate carriers.
#### Description of issue

When you try to add an accessory to a plate carrier, like arm guards or legs guards, the game won't let you saying it doesn't accept said accessory. This also happens when you remove the plate storage accessory from the plate carrier, you won't be able to add it again.

#### Difference between expected and actual behavior

The game should let you add accessories into the plate carriers.

#### Steps to reproduce 
1A. Get a plate carrier
2A. Try to add a leg or arm guard. You can't.
1B. Remove the storage accessory
2B. Try to add it again, the game doesn't let you.

#### Specific information for locating

Plate carrier.

#### Length of time in which bug has been known to occur

In the last 2 rounds of 7th of June, 2020

#### Client version, Server revision & Game ID

Couldn't get it but the revision and ID was from 7th of June, 2020

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/DS-13-Dev-Team/DS13/issues)

### LINKED ISSUE #446: BUG: Minor text fix in skill panel
#### Description of issue
https://i.imgur.com/QckW0WM.png
Complex Devices doesn't have a category.

#### Specific information for locating

Skill panel

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: b5a671a7c02dc069f00f1fbc0f593d8005a1691e - dev - 2020-06-19
Game ID: b7K-c3xt
Current map: USG Ishimura

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/DS-13-Dev-Team/DS13/issues)

### PR DESCRIPTION
**Pull request by JakeDaBoss**
Fixes four issues.

Closes #446
Closes #307 
Closes #418 
Closes #125

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Also closes #446

**Comment by JakeDaBoss** [comment]
Latest commit was meant to mention #544 not 554.

**Comment by Snypehunter007** [comment]
Just looking over this, I have some comments, @JakeDaBoss 

- Plate Carriers don't really fit with the Dead Space style, at this time, we are not going to implement them, pending a further review. So you don't need to do fixes for them, it is likely they'll be removed in the future.

- Bowman headsets were also left out intentionally, they do not fit with the non-military version of Security. Those can be removed all together if you want.

- Unsure on adding the gas masks, by default, to the security belts, there should be enough lockers for every officer to get one anyways from their locker.

- The name of the .YML change-log file should be `CKEY-PR-#`, this way , if someone doesn't label their change-log name the same as the branch name, I don't have to hunt and figure out which PR the change-log is for.

- Another point regarding the change-log you don't need to add the, `Fixes issue #125 (Reported by SnypeHunter)` on the first line. Along with that, on the second line about gas masks, you shouldn't add, `Currently does not work on other holster. Fixes point 1 through 3. Rest will not be pursued.` Nobody in-game is going to know what that means about point 1-3 or what the "rest" entails. The point of the change-log is for players in-game to know of fixes that are pertinent to them. This line would be something you would add to the Github specific description.

**Comment by JakeDaBoss** [comment]
> Just looking over this, I have some comments, @JakeDaBoss
> 
> * Plate Carriers don't really fit with the Dead Space style, at this time, we are not going to implement them, pending a further review. So you don't need to do fixes for them, it is likely they'll be removed in the future.
> * Bowman headsets were also left out intentionally, they do not with with the non-military version of Security. Those can be removed all together if you want.
> * Unsure on adding the gas masks, by default, to the security belts, there should be enough lockers for every officer to get one anyways from their locker.
> * The name of the .YML change-log file should be `CKEY-PR-#`, this way , if someone doesn't label their change-log name the same as the branch name, I don't have to hunt and figure out which PR the change-log is for.
> * Another point regarding the change-log you don't need to add the, `Fixes issue #125 (Reported by SnypeHunter)` on the first line. Along with that, on the second line about gas masks, you shouldn't add, `Currently does not work on other holster. Fixes point 1 through 3. Rest will not be pursued.` Nobody in-game is going to know what that means about point 1-3 or what the "rest" entails. The point of the change-log is for players in-game to know of fixes that are pertinent to them. This line would be something you would add to the Github specific description.

I'll be working on these changes tomorrow. I'll be removing pcarriers and bowman headsets altogether, and work on the remaining issues.

**Comment by NanakoAC** [comment]
We've had some miscommunication about the plate carriers, don't remove anything there, just do the fix for attachments

**Comment by NanakoAC** [comment]
Also, mentioning issues in commits does not work, and probably not comments either.

To properly link an issue, you need to mention it in the PR description, like 

Closes #544

**Comment by NanakoAC** [comment]
And while not using bowman headsets is fine, that's no reason to delete things from the codebase at random, we may want to use them in future for response teams.

Unless things are causing a problem, there's no need to delete unused content

**Comment by JakeDaBoss** [comment]
> And while not using bowman headsets is fine, that's no reason to delete things from the codebase at random, we may want to use them in future for response teams.
> 
> Unless things are causing a problem, there's no need to delete unused content

I was asked by Snype.

Platecarriers aren't removed, but áre fixed.

I also unfortunately realized my mistake in the PR Commit, but I added a comment after-the-fact so it may be manually closed when/if it is merged.

**Comment by NanakoAC** [comment]
The issue links can be edited into the PR description, please do so before we merge it

**Review by NanakoAC — APPROVED** [review]

**Pull request merged**
